name: Version test
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Release type (one of): patch, minor, major, prepatch, preminor, premajor, prerelease"
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
        with:
          clean: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://npm.pkg.github.com"
      - name: Git configuration
        run: |
          git config --global user.email "opensource@gcismet.de"
          git config --global user.name "GitHub Actions"
      - name: Change release version
        run: npm version ${{ env.RELEASE_TYPE }}
        env:
          RELEASE_TYPE: ${{ github.event.inputs.release-type }}
      # - name: Install Packages
      #   run: yarn install
      # - name: Build the package
      #   run: yarn build:package
      # - name: Publish the package
      #   run: cd dist && npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: debug
      #   run: echo ${{ github.ref }} && echo ${{ github.head_ref }}
      - name: Push changes to repository
        run: |
          git add package.json
          git commit -am "version bump from github action"
          git push origin dev
